### ISSUE TITLE
gnome-pomodoro segfaults if sent SIGTERM with window open

### ISSUE THREAD

**Issue by mattst88** [gnome-pomodoro/gnome-pomodoro#690]
Start gnome-pomodoro from the terminal. With the window still open, press CTRL+C in the terminal. gnome-pomodoro segfaults:

```
mattst88@framework ~ $ gnome-pomodoro      

** (gnome-pomodoro:1700149): WARNING **: 13:00:39.679: gnome-shell-extension.vala:244: Failed to load extension: 

** (gnome-pomodoro:1700149): WARNING **: 13:00:39.679: gnome-shell-extension.vala:244: Failed to load extension: 
^C[1]    1700149 segmentation fault (core dumped)  gnome-pomodoro
```

If you close the gnome-pomodoro window and then press CTRL+C, it exits gracefully.

Running it in `gdb` and `kill`'ing it from another terminal (which sends `SIGTERM`, not `SIGINT`) also triggers the segfault:

```
** (gnome-pomodoro:1700537): WARNING **: 13:06:20.119: gnome-shell-extension.vala:244: Failed to load extension: 

** (gnome-pomodoro:1700537): WARNING **: 13:06:20.119: gnome-shell-extension.vala:244: Failed to load extension: 

Thread 1 "gnome-pomodoro" received signal SIGTERM, Terminated.
0x00007ffff7ac90ff in poll () from /usr/lib64/libc.so.6
(gdb) c
Continuing.

(gnome-pomodoro:1700537): GLib-GObject-CRITICAL **: 13:06:26.755: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(gnome-pomodoro:1700537): Gtk-CRITICAL **: 13:06:26.755: gtk_application_remove_window: assertion 'GTK_IS_WINDOW (window)' failed

Thread 1 "gnome-pomodoro" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f45d39 in pomodoro_application_real_shutdown (base=0x55555557e520) at src/libgnome-pomodoro.so.0.0.0.p/application.c:2335
2335				_tmp1_ = _g_object_ref0 ((GtkWindow*) window_it->data);
(gdb) bt
#0  0x00007ffff7f45d39 in pomodoro_application_real_shutdown (base=0x55555557e520) at src/libgnome-pomodoro.so.0.0.0.p/application.c:2335
#1  0x00007ffff7d20a3a in ??? () at /usr/lib64/libgobject-2.0.so.0
#2  0x00007ffff7d20b56 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#3  0x00007ffff7d20c1b in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#4  0x00007ffff7e300d2 in g_application_run () at /usr/lib64/libgio-2.0.so.0
#5  0x0000555555555335 in _vala_main (args=0x7fffffffd928, args_length1=1) at src/gnome-pomodoro.p/main.c:100
#6  0x0000555555555394 in main (argc=1, argv=0x7fffffffd928) at src/gnome-pomodoro.p/main.c:111
(gdb) p window_it
$1 = 0x600000002 = {Cannot access memory at address 0x600000002
```
Looks like `window_it` is invalid.

**Comment by kamilprusko** [comment]
This change 46b1713d2a640428344802c0d463c47e3d5e8fb1 seems to fix this

**Comment by mattst88** [comment]
Confirmed, thanks!
